// Generated by CoffeeScript 1.12.7

/*

Параметры:

  wall_offset  - отступ от стены [мм]
  board_w      - ширина доски [мм]
  board_h      - высота доски [мм]
  room_polygon - полигон комнаты 
  room_polygon_offset - полигон комнты с отсупом 
  room_bbox    - габариты комнаты
  flooring[]   - массив ламинатин
  
Алгоритм:
 */

(function() {
  $(function() {
    var s;
    return s = Snap(360, 640);
  });

}).call(this);
